name: Install subrepo templates

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  install-templates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install git-subrepo
        shell: bash
        run: |
          git clone https://github.com/ingydotnet/git-subrepo ~/.git-subrepo
          export PATH="$HOME/.git-subrepo/lib:$PATH"
          git subrepo --version

      - name: Configure git identity for commits
        shell: bash
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Run installer
        shell: bash
        run: |
          set -euo pipefail
          curl -fsSL https://raw.githubusercontent.com/pmalacho-mit/subrepo-dependency-management/refs/heads/main/scripts/install-templates.sh | bash -s --
